version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-gin-app
    ports:
      - "8080:8080"
    environment:
      - DBHOST=postgres
      - DBPORT=5432
      - DBUSER=postgres
      - DBPASSWORD=postgres
      - DBNAME=todo
      - PORT=8080
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
