// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"go-gin-project/api/controller"
	"go-gin-project/api/repository"
	"go-gin-project/api/service"
	"go-gin-project/config"
)

// Injectors from injection.go:

func InitializeTagsController() *controller.TagsController {
	db := config.DatabaseConnection()
	tagsRepository := repository.NewTagsREpositoryImpl(db)
	validate := config.NewValidator()
	tagsService := service.NewTagsServiceImpl(tagsRepository, validate)
	tagsController := controller.NewTagsController(tagsService)
	return tagsController
}
